coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%

ignore:
  - "delivery-service/**/*"  # ignore PoC DS server and lib
  - "emulated_client/**/*"  # ignore PoC emulated_client
  # ignore test frameworks
  - "openmls/tests/utils/managed_utils/*"
  - "openmls/tests/utils/mls_utils/*"
